services:
  aws-dev:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: cdcp-xslt-processing-aws-dev
    env_file:
      - env
    environment:
      ENVIRONMENT: aws-local
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
      ANT_TARGET: ${ANT_TARGET:-full}
    ports:
      - 9000:8080
